# Generated by Django 5.1.1 on 2024-10-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apaterno',
            field=models.CharField(max_length=50, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterModelTable(
            name='alumno',
            table='Alumnos',
        ),
    ]
